// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicEventManagementSystem.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicEventManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250926120000_UpdatePhaseSystemModel")]
    partial class UpdatePhaseSystemModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This is a simplified target model - EF Core will generate the full one
            // The key changes are:
            // - Added CurrentPhaseOrder to Negotiations
            // - Added IsRequired and UpdatedAt to Requirements
            // - Removed Fulfilled from Requirements
            // - Added NegotiationPhases table
            // - Added NegotiationRequirementFulfillments table
#pragma warning restore 612, 618
        }
    }
}